[package]
name = "mlang"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
eframe = "0.31.1"
egui = "0.31.1"
egui_commonmark = "0.20.0"
egui_extras = "0.31.1"
rfd = "0.15.3"
